title: Pure Writer
email: drakeet.me@gmail.com
theme: jekyll-theme-minimal
logo: images/s720.png
logo_full: images/s.png
show_downloads: true
google_play: https://play.google.com/store/apps/details?id=com.drakeet.purewriter
coolapk: https://www.coolapk.com/apk/com.drakeet.purewriter
direct: http://app.mi.com/download/466749